[#9] 작업물 추가 기능 구현
f-lab-edu/sound-hub pull request #11
Opened 2024-04-27 01:15 UTC by dhchoi98

## 연관된 이슈

> https://github.com/f-lab-edu/sound-hub/issues/9

## 작업 내용

>  작업물 추가 기능에 관련된 클래스들 구현

### 스크린샷 (선택)

## 리뷰시 참고사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-04-28 04:32 UTC, blue000927 approved these changes
깔끔하네요~! 몇가지 마이너 피드백만 적용해주세요.

2024-04-28 04:32 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/Work.java
> +	public Work(Long userId, String name, WorkType workType, String youtubeUrl, String workImageUrl) {
18L 지우기

2024-04-28 04:32 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/Work.java
> +	private Long id;
웬간하면 id는 필드 순서상 맨위로 올려주세요!

2024-04-28 04:32 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/dao/WorkDao.java
> +	public Work create(Work work) {
트랜잭션은 서비스 레이어와 DAO 중 어디에 붙이는 것이 좋다고 생각하시나요?

2024-04-28 14:17 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/dao/WorkDao.java
> +	public Work create(Work work) {
서비스 계층에다가 Transactional을 붙이게 되면 여러 DAO 호출에 대한 트랜잭션을 한꺼번에 관리할 수 있으므로 더 효율적입니다.
코드 수정하겠습니다 !!

2024-05-07 16:18 UTC, blue000927 requested changes

2024-05-07 16:18 UTC, blue000927 commented on .github/PULL_REQUEST_TEMPLATE.md
> +> 이번 PR에서 작업한 내용을 간략히 설명해주세요 (이미지 첨부 가능)
요런 템플릿은 다음부터 PR 분리하여 올려주세요!

2024-05-07 16:18 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +		}
DatabaseException이 맞을까요?

2024-05-07 16:18 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +
@RequestHeader("Authorization")를 통해서 token을 가져오고, 그 토큰의 페이로드인 user_id를 추출하면 어떨까요?

2024-05-07 16:18 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
>  	}
UserService에 대한 테스트 코드 작성 부탁드립니다!

2024-05-07 16:18 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +public class WorkService {
테스트 코드 추가해주세요!

2024-05-07 16:18 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +		if (image.getSize() > 0) {
사이즈가 0일 수가 있나요??

2024-05-09 08:43 UTC, dhchoi98 commented on .github/PULL_REQUEST_TEMPLATE.md
> +> 이번 PR에서 작업한 내용을 간략히 설명해주세요 (이미지 첨부 가능)
넵 !

2024-05-09 08:45 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +
감사합니다

2024-05-09 08:50 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
>  	}
토큰 생성에 대한 로직을 추가하면 되는건가요??

2024-05-09 12:33 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
>  	}
UserService의 행위(메서드)들에 대해 모두입니다.

2024-05-10 07:53 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +		}
수정 커밋 완료했습니다~!

2024-05-11 02:03 UTC, blue000927 approved these changes
조금 늘어지는 것 같아서 테스트 코드는 따로 이슈 파서 진행하는 것으로 합시다.
테스트 코드 외의 내용만 일단 반영해 주시고, 테스트 코드 개선하기 이슈 하나 파주세요!

2024-05-11 02:03 UTC, blue000927 commented on build.gradle
> +
rm

2024-05-11 02:03 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/S3Service.java
> +	private final AmazonS3 amazonS3Client;
localStack 활용하여 S3ServiceTest 코드 작성 부탁드립니다!

2024-05-11 02:03 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +		if (image.getSize() > 0) {
요거 답변 부탁드립니다.

2024-05-11 02:03 UTC, blue000927 commented on src/main/java/com/example/soundhub/config/exception/ExceptionAdvice.java
> +	public ResponseEntity<ErrorResponse> handleAwsS3Exception(DatabaseException ex) {
DatabaseException -> AwsS3Exception

2024-05-11 02:03 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtInterceptor.java
필드 주입으로 한 이유가 있나요?

2024-05-11 02:03 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtUtil.java
> +		Long userId = Long.parseLong(result);
로직이 생각보다 복잡도가 있어서 JwtUtilTest가 있으면 좋겠네요.

2024-05-11 02:03 UTC, blue000927 commented on src/test/java/com/example/soundhub/LocalStackDockerExtensionTest.java
> +class LocalStackDockerExtensionTest {
이건 제거하기 (예시용이라)

2024-05-11 02:03 UTC, blue000927 commented on src/test/java/com/example/soundhub/controller/WorkControllerTest.java
> +		// Implement token retrieval logic, possibly mocking the authentication call
주석들은 없애주세요!

2024-05-11 02:03 UTC, blue000927 commented on src/test/java/com/example/soundhub/service/WorkServiceTest.java
> +public class WorkServiceTest {
웬만하면 Mock을 사용한 단위 테스트보다는 통합 테스트로 연습해 보시면 좋겠습니다.

2024-05-12 10:55 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +		if (image.getSize() > 0) {
이미지가 null로 들어왔을 때의 처리를 저런 방식으로 했었습니다 !

2024-05-12 10:56 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +public class WorkService {
넵

2024-05-12 10:58 UTC, dhchoi98 commented on build.gradle
> +
localStack 사용 라이브러리 아닌가요??

2024-05-12 14:01 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/S3Service.java
> +	private final AmazonS3 amazonS3Client;
넵

2024-05-12 14:52 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/config/exception/ExceptionAdvice.java
> +	public ResponseEntity<ErrorResponse> handleAwsS3Exception(DatabaseException ex) {
커밋 완료했습니다 !

2024-05-12 14:54 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/jwt/JwtInterceptor.java
수정 하겠습니다!

2024-05-12 14:57 UTC, dhchoi98 commented on src/test/java/com/example/soundhub/service/WorkServiceTest.java
> +public class WorkServiceTest {
넵 알겠습니다

2024-05-14 13:28 UTC, blue000927 commented on build.gradle
> +
아 통으로 지우라는건 아니고 57, 58번째 라인이 불필요하게 있어서 들여쓰기 지우면 어떨까 했습니다.

2024-05-14 13:29 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +		if (image.getSize() > 0) {
null인 이미지가 Service까지 들어오지 않도록 Controller 단에서 막으면 어떨까요?

2024-05-14 13:30 UTC, blue000927 approved these changes
마이너 리뷰 반영해 주시고 머지합시다!

2024-05-15 05:04 UTC, dhchoi98 commented on build.gradle
> +
앗 감사합니다 !!

2024-05-15 05:04 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/WorkService.java
> +		if (image.getSize() > 0) {
넵 수정하겠습니다 !!

2024-05-16 05:07 UTC, merged