Feature/12/s3 img
f-lab-edu/sound-hub pull request #13
Opened 2024-04-27 06:37 UTC by dhchoi98

## 연관된 이슈

* https://github.com/f-lab-edu/sound-hub/issues/12

## 작업 내용

* S3 이미지 업로드, 삭제 기능 추가

## 리뷰시 참고사항

2024-04-28 04:36 UTC, blue000927 requested changes

2024-04-28 04:36 UTC, blue000927 commented on .gitignore
> +application-private.yml
application-private.yml을 추가하기보다는 기존 application.yml에 S3 관련한 값을 환경 변수로 추가하면 어떨까요?

2024-04-28 04:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +	}
해당 작업은 테스트 코드에서 부탁드립니다.

2024-04-28 04:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +			try {// 파일 업로드
주석 제거

2024-04-28 04:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +		String profileImage = "";
업로드 실패하면 에러를 던지면 될 것 같은데, 왜 기본값인 ""을 200번 상태 코드와 함께 반환하도록 하셨나요?

2024-04-28 04:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/S3Service.java
> +
테스트 코드는 어떻게 짜면 좋을까요?
(힌트: localstack)

2024-04-28 12:13 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +	}
넵

2024-04-28 12:13 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +		String profileImage = "";
테스트만 간단하게 하느라 신경을 못썼습니다 ㅠ

2024-04-28 12:14 UTC, dhchoi98 commented on .gitignore
> +application-private.yml
테스트 yml파일에도 환경변수로 가져오면 되는건가요??

2024-04-29 12:34 UTC, pjy1368 commented on src/main/java/com/example/soundhub/application/service/S3Service.java
> +
https://steady-coding.tistory.com/644

2024-04-30 03:36 UTC, merged