[#12] 이미지 업로드 기능 구현 - 13번 PR 수정
f-lab-edu/sound-hub pull request #14
Opened 2024-05-03 07:25 UTC by dhchoi98

## 연관된 이슈

* #12 #13 

## 작업 내용

* application-private.yml 지우기

* S3Service에서 정의된 upload() 메서드에 대한 검증 코드 추가

### 스크린샷 
![image](https://github.com/f-lab-edu/sound-hub/assets/104803789/f6f2b112-e64e-4ac8-bab8-2216023a691a)

## 리뷰시 참고사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-05-06 06:10 UTC, blue000927 requested changes

2024-05-06 06:10 UTC, blue000927 commented on .gitignore
> +application-private.yml
요거 지워주세요!

2024-05-06 06:10 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +	}
다음 PR에서 제거해주시고, 테스트 코드로 검증해주세요!

2024-05-06 06:10 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +				System.out.println("fileURL = " + profileImage);
System.out.println()을 로깅용으로 사용하셨는데, 이렇게 사용하면 어떤 문제가 있을까요?

2024-05-06 06:10 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +		return ResponseEntity.ok(profileImage);
업로드 실패하면 에러를 던지면 될 것 같은데, 왜 기본값인 ""을 200번 상태 코드와 함께 반환하도록 하셨나요?
(이전 PR에서 말씀드린 내용이 반영안됐네요!)

2024-05-06 06:10 UTC, blue000927 commented on src/main/resources/application.yml
> +    include: private
제거하기

2024-05-06 06:10 UTC, blue000927 commented on src/main/resources/application.yml
> +    root: debug
aws 관련 설정 key 값은 어디에 있나요?

2024-05-06 06:10 UTC, blue000927 commented on src/test/java/com/example/soundhub/LocalStackDockerExtensionTest.java
> +}
S3ServiceTest 따로 만들어서 S3Service에 있는 메서드들을 모두 검증해주세요!
위 테스트 코드는 제가 예제로 드린 것이므로 이것을 참고하여 S3ServiceTest를 작성해 주시고 LocalStackDockerExtensionTest는 제거해주세요.

2024-05-20 15:30 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +	}
넵 !

2024-05-20 15:31 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +				System.out.println("fileURL = " + profileImage);
로그 기록에 남지 않는 문제가 있을 것 같습니다 삭제하겠습니다 !

2024-05-20 15:31 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/WorkController.java
> +		return ResponseEntity.ok(profileImage);
업로드 관련 메소드 전부 삭제하겠습니다 ㅎㅎ

2024-05-20 15:32 UTC, dhchoi98 commented on src/test/java/com/example/soundhub/LocalStackDockerExtensionTest.java
> +}
네 테스트 관련 반영 내용 전부 테스트 브랜치에서 수정하도록 하겠습니다 !

2024-05-21 07:46 UTC, blue000927 approved these changes

2024-05-23 09:49 UTC, merged