[#18] 나의 소개 등록, 수정, 조회
f-lab-edu/sound-hub pull request #19
Opened 2024-05-23 09:50 UTC by dhchoi98

## 연관된 이슈

*  #18 

## 작업 내용

- [x] 프로필 도메인 추가
- [x] 나의 소개 등록
- [ ] 나의 소개 편집
- [ ] 나의 소개 조회

### 스크린샷

## 리뷰시 참고사항

2024-05-24 11:53 UTC, blue000927 requested changes
코멘트들 잘 고민해 보세요!

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +
매번 image의 사이즈를 체크하고 0보다 작으면 예외를 던지는 코드들이 중복해서 나오고 있는데 어떻게 해결하면 좋을까요?

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/Profile.java
> +	private final String favoriteArtistFifth;
만약 좋아하는 아티스트의 종류가 늘어나면 그때마다 필드를 추가해줘야하고, 반대로 종류가 줄어들면 필드를 제거해야 합니다.
또한, 클라이언트 입장에서도 굳이 여러 개의 필드를 처리하는 것은 좋은 경험이 아닐 것 같은데 어떻게 생각하시나요?

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		System.out.println("profile.getBackgroundImgUrl() = " + profile.getBackgroundImgUrl());
System.out.println()을 이렇게 사용하면 어떤 문제점이 있을까요?

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/mapper/ProfileMapper.java
> +	@Select("SELECT user_id, genre, position, introduce, background_img_url, favorite_artist_first, favorite_artist_second, favorite_artist_third, favorite_artist_fourth, favorite_artist_fifth FROM prof
요거는 SELECT * 로 하지 않은 이유가 있나요?

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		Profile Result = profileDao.update(profile);
이러면 Profile의 id가 null이 되어서, 실제 profile DB에는 id가 null로 업데이트되지 않나요?

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/dto/response/UserResponse.java
> +		private boolean isMyProfile;
사용하는 클라이언트 입장에서 보낼 때 user_id와 받았을 때 user_id 비교하면 MyProfile인지 아닌지 판단할 수 있을 것 같은데, 해당 필드는 없어도 되지 않을까요?

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +	@PostMapping("/change-profile")
@PostMapping으로 사용하신 이유가 있나요?

2024-05-24 11:53 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +
이러면 다른 유저의 ID만 알 수 있으면, 다른 유저의 Profile도 업데이트할 수 있게 되지 않을까요?

2024-05-24 13:53 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/mapper/ProfileMapper.java
> +	@Select("SELECT user_id, genre, position, introduce, background_img_url, favorite_artist_first, favorite_artist_second, favorite_artist_third, favorite_artist_fourth, favorite_artist_fifth FROM prof
SELECT * 로 했을 때 BackgroundImage가 null 값인데도 introduce의 값이 밀려서 나오는 현상이 발생해서 수정했습니다

2024-05-24 13:56 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		System.out.println("profile.getBackgroundImgUrl() = " + profile.getBackgroundImgUrl());
오류 잡으려고 써놨었는데 미처 지우는 것을 깜빡했네요 ㅠㅠ 로깅을 println으로 하게되면 기록이 남지않고 성능저하의 원인이 됩니다

2024-05-24 13:59 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		Profile Result = profileDao.update(profile);
![image](https://github.com/f-lab-edu/sound-hub/assets/104803789/e68e28f0-3d55-4b08-a3fc-e7143a452c77)
실제 적용해보니 null이 업데이트 되는 오류가 발생하지는 않았습니다 아마 Mapper.xml에서 insert 할 때 profile_id는 넣어주지 않아서 그런 것 같습니다

2024-05-24 14:05 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +	@PostMapping("/change-profile")
Post가 안전하다고 들었던 기억에 습관적으로 썼습니다 ㅎㅎ 제대로 공부해보면서 수정하겠습니다

2024-05-24 14:08 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +
메소드로 빼면 될까요??

2024-05-24 14:15 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/domain/Profile.java
> +	private final String favoriteArtistFifth;
원래 기획단계에서 생각했을때는 5명으로 제한하려고 했으나 한 번 말씀해주신 상황을 경험 해보는 게 좋을 것 같아서 배열 필드로 수정 하던 중 MyBatis 에서는 배열 필드를 쓰는게 좀 까다로워서 (타입 핸들러를 작성해주어야 되는걸로 알고 있습니다)  프로젝트 진행 시간 관계상 일단은 저렇게 필드로 분리해놨습니다 ㅠㅠ

2024-05-24 14:21 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +
토큰안에 있는 유저 id를 통해서 업데이트 하는데도 방어할수가 없는건가요??

2024-05-24 16:53 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/dto/response/UserResponse.java
> +		private boolean isMyProfile;
받을 때 Response 값에는 token안에 있는 userId를 보내주면 되는건가요??

2024-05-26 04:38 UTC, pjy1368 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +
어떻게 메서드로 분리하실 생각이실까요?
이미지 업로드 로직이 UserService 외에 더 생길수도 있는데, UserSevice, WorkService 등에 동일한 메서드를 추가하는 것도 중복이지 않을까요?

2024-05-26 04:38 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +
어떻게 메서드로 분리하실 생각이실까요?
이미지 업로드 로직이 UserService 외에 더 생길수도 있는데, UserSevice, WorkService 등에 동일한 메서드를 추가하는 것도 중복이지 않을까요?

2024-05-26 04:39 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/Profile.java
> +	private final String favoriteArtistFifth;
배열로 변환하는 방법이 많이 어려울까요? 요거는 enum과 다르게 코드 퀄리티 좀 많이 떨어뜨리는 것 같아서 가능하면 진행했으면 합니다.

2024-05-26 04:40 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/mapper/ProfileMapper.java
> +	@Select("SELECT user_id, genre, position, introduce, background_img_url, favorite_artist_first, favorite_artist_second, favorite_artist_third, favorite_artist_fourth, favorite_artist_fifth FROM prof
BackgroundImage가 null인데도 introduce의 값이 밀려서 나오는 이유가 뭔가요??

2024-05-26 04:41 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		Profile Result = profileDao.update(profile);
Profile을 create하고 난 다음, changeProfile을 할 때 id는 null이 아닌 원본 값(ex. 3)으로 유지가 되는 것이 맞을까요?

2024-05-26 04:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/dto/response/UserResponse.java
> +		private boolean isMyProfile;
흠 요거 다시 생각해보니까 MyProfile인지 아닌지 구분해야할 이유가 있나요? 조회는 다 허용하고, 수정만 막으면 될 것 같은데 어떻게 생각하시는지 궁금합니다.

2024-05-26 04:45 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +	@PostMapping("/change-profile")
왜 Post가 안전하고, chage 행위에 Post를 사용했는지 학습해보시고 알려주세요!
Post가 적절하지 않다면 무엇으로 대체해야하는지도 고민해보세요~

2024-05-26 04:48 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +
JWT가 탈취될 수 있다는 점을 고려해서 작성해보면 좋을 것 같아요! 다른 유저의 토큰을 가져와서 호출해버릴 수 있습니다.

2024-05-26 17:04 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +
고민해보겠습니다..!!

2024-05-26 17:04 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/domain/Profile.java
> +	private final String favoriteArtistFifth;
넵 진행 하도록 하겠습니다 !!

2024-05-27 06:42 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/mapper/ProfileMapper.java
> +	@Select("SELECT user_id, genre, position, introduce, background_img_url, favorite_artist_first, favorite_artist_second, favorite_artist_third, favorite_artist_fourth, favorite_artist_fifth FROM prof
찾지는 못했습니다..

2024-05-28 05:22 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/mapper/ProfileMapper.java
> +	@Select("SELECT user_id, genre, position, introduce, background_img_url, favorite_artist_first, favorite_artist_second, favorite_artist_third, favorite_artist_fourth, favorite_artist_fifth FROM prof
그렇군요..! 일단 그렇게 진행해주세요

2024-05-28 05:23 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		Profile Result = profileDao.update(profile);
네 그렇게 되어야 합니다. 만약 null로 되면 문데가 있습니다.

2024-05-29 12:08 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/mapper/ProfileMapper.java
> +	@Select("SELECT user_id, genre, position, introduce, background_img_url, favorite_artist_first, favorite_artist_second, favorite_artist_third, favorite_artist_fourth, favorite_artist_fifth FROM prof
넵 !

2024-05-29 12:09 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		Profile Result = profileDao.update(profile);
그럼 이대로 진행하면 될까요??

2024-05-29 12:17 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +	@PostMapping("/change-profile")
네 알겠습니다 !

2024-05-29 12:17 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +
네 공부해서 수정하겠습니다 !!

2024-05-30 15:35 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/dto/response/UserResponse.java
> +		private boolean isMyProfile;
![image](https://github.com/f-lab-edu/sound-hub/assets/104803789/c28c5834-f610-46cb-b7df-072f18a2a453)
![image](https://github.com/f-lab-edu/sound-hub/assets/104803789/977874a1-05a3-4a0a-a080-7f706c0068fc)

2024-06-01 14:06 UTC, blue000927 approved these changes
고생하셨습니다!

2024-06-01 14:06 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		}
image size 체크하는 로직도 s3Service.upload()에서 처리하면 어떨까요?

2024-06-01 14:06 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		favoriteArtists.add(request.getFavoriteArtistFifth());
왜 여기는 좋아하는 아티스트 컬럼이 1개가 아닌 5개인가요?

2024-06-01 14:06 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/handler/StringListTypeHandler.java
> +		// 리스트를 콤마로 구분된 하나의 문자열로 변환
주석이 없어도 괜찮습니다.

2024-06-02 05:47 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		favoriteArtists.add(request.getFavoriteArtistFifth());
현재 request에서 받을 때는 배열 형태로 한 번에 받는 것이 아닌 기존 방식 그대로 받고 있습니다
추후 5명 이상 받는 것으로 수정할 때 바꾸려고 했는데 통일성을 위해 그냥 클라이언트에서도 한꺼번에 받는 것으로 수정하는 것이 좋을까요?

2024-06-02 05:51 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +		}
수정하도록 하겠습니다 !!

2024-06-02 05:51 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/handler/StringListTypeHandler.java
> +		// 리스트를 콤마로 구분된 하나의 문자열로 변환
넵 ㅎㅎ

2024-06-02 07:08 UTC, merged