[FEAT] #5 : 회원가입 기능 구현
f-lab-edu/sound-hub pull request #6
Opened 2024-03-31 08:56 UTC by dhchoi98

2024-03-31 09:52 UTC, pjy1368 commented
PR 본문에는 이슈 링크를 연결해 주시고, 이 PR에서 작업하신 내용을 추가로 작성해주세요.
(이미 이슈에 작업 내용이 있으니, 3줄 요약하는 느낌으로 간단하게!)

[예시]
## 개요
- Issue: {issue_링크}
- 어떤 방식의 회원 가입을 구현하였음.
- (기타 코드적으로 구현한 내용을 필요하다면 작성)

## 리뷰시 참고 사항
- 리뷰어에게 의견이 필요하거나, 리뷰어가 중점적으로 보면 좋을 부분을 나열해주세요
(코멘트로 남겨주셔도 좋습니다)

2024-03-31 09:53 UTC, pjy1368 commented
추가로 PR은 처음 보는 사람도 이해할 수 있도록 적어야 합니다!
회원 가입 방식만 하더라도 수십가지가 있을 것이고, 어떻게 구현하였는지는 천차만별입니다.
그래서 PR 본문에 처음 보는 독자를 배려하여 글을 작성하는 습관을 기르시면 좋겠습니다.

2024-03-31 10:09 UTC, pjy1368 requested changes
우선, 전체적으로 code formatting 한번 부탁드립니다!
그리고 테스트 코드가 작성되어 있지 않은데, 가능한 모든 레이어에 대해 테스트 코드 작성 부탁드립니다.

2024-03-31 10:09 UTC, pjy1368 commented on build.gradle
> +
저와의 프로젝트에서 스프링 시큐리티는 사용하지 않는 걸로 할게요!
스프링 시큐리티 없이 순수하게 구현해 보는 연습을 하셔야 내부 동작을 이해하기 좋습니다 :)

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +
\n 하나 제거

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +
\n 하나 제거

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +    public String createUser(UserRequest.join req) {
가능한 줄임말은 쓰지 않으셨으면 합니다 ㅎㅎ request로라도 써주시죠

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/common/util/UuidUtil.java
> +                (timeForUuidIn100Nanos & 0xFFFFFFFFFFFF0000L) + version + least12SignificatBitOfTime;
한 줄로 써볼까요?

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/common/util/UuidUtil.java
> +    }
java.util.UUID 라이브러리가 있는데 이렇게 복잡하게 구현하신 이유가 있을까요??

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        UserRow userRow = userMapper.find(uuid);
create와 동시에 UserRow를 반환하는 방법은 없을지 찾아봐주세요!

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/domain/model/User.java
> +public record User(Long userIdx, String uuid, String name, String id, String password) {
userIdx와 uuid는 어떠한 용도로 쓰이나요?

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/infrastructure/mapper/UserMapper.java
> +// Repository
주석 제거

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/infrastructure/mapper/UserMapper.java
> +    int create(String uuid, String name, String id, String password);
create할 때 User domain을 파라미터로 넘기는 방식으로 구현해 보면 어떨까요?

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/infrastructure/model/UserRow.java
> +// Entity
주석 제거

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/infrastructure/model/UserRow.java
> +    private final String uuid;
userIdx와 uuid가 동시에 들어가는데 어떤 용도로 쓰이나요?

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +public class UserController {
`@Slf4j`는 현재 사용되지 않고 있네요~

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/presentation/dto/JsonResponse.java
> +    private int status;
200, 201, 404 등의 상태 코드는 ResponseEntity를 통해 표현이 가능한데 Response에 status를 넣어야 할 필요가 있을까요?
비슷한 맥락으로 상태 코드보고 isSuccess를 판단할 수 있어 보이네요!

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +         return ResponseEntity.ok(new JsonResponse(true, 200, userName));
userName만 필요한가요? 프로토 타이핑한 UI 입장에서 필요한 필드를 고민해 보시면 좋을 것 같네요~

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +    public ResponseEntity<JsonResponse> join(@RequestBody UserRequest.join req) {
req 대신 완성된 용어로 작성해주세요!

2024-03-31 10:09 UTC, pjy1368 commented on src/main/java/com/example/soundhub/presentation/dto/response/UserResponse.java
> +}
사용하지 않는다면 제거해 주시죠!

2024-03-31 10:47 UTC, dhchoi98 commented on build.gradle
> +
네 알겠습니다 !

2024-03-31 10:50 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/dto/JsonResponse.java
> +    private int status;
그럼 JsonRepsponse 클래스는 삭제하고 ResponseEntity를 사용하여 반환하는 것이 좋을까요?

2024-03-31 10:53 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/common/util/UuidUtil.java
> +    }
예전 프로젝트에서 사용했던 방법인데 라이브러리 사용하는 법은 모르고 있었습니다.. ㅎㅎ

2024-03-31 10:55 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +         return ResponseEntity.ok(new JsonResponse(true, 200, userName));
회원가입시에는 회원가입 성공 메세지만 반환하고 로그인시에 토큰 발급하는 형식으로 구현하려고 했는데
바로 접속 가능하도록 구현하는 것이 좋을까요??

2024-03-31 10:55 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        UserRow userRow = userMapper.find(uuid);
네 알겠습니다 !!

2024-03-31 10:57 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/domain/model/User.java
> +public record User(Long userIdx, String uuid, String name, String id, String password) {
userIdx : Primary Key (DB 및 서버 프로그램 내부)
uuid : Response 반환 값 등에서 userIdx 대신 사용 
( 프론트와 통신에서 유저의 Primary Key가 노출되면 안좋다고 알고있어서 만들었습니다.)

2024-03-31 10:58 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/model/UserRow.java
> +    private final String uuid;
UserRow = JPA에서 엔티티 
라고 이해하고 있어서 모든 컬럼들을 작성 해주었습니다.

userIdx와 uuid의 용도는

userIdx : Primary Key (DB 및 서버 프로그램 내부)
uuid : Response 반환 값 등에서 userIdx 대신 사용
( 프론트와 통신에서 유저의 Primary Key가 노출되면 안좋다고 알고있어서 만들었습니다.)

로 분할했습니다.

2024-03-31 10:59 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +public class UserController {
제거하겠습니다 !!

2024-03-31 11:09 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        UserRow userRow = userMapper.find(uuid);
메서드 반환값을 UserRow로 세팅하는 방식인가요?

2024-03-31 11:10 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/mapper/UserMapper.java
> +    int create(String uuid, String name, String id, String password);
User domain을 생성하려면 idx가 있어야 하는데 현재 idx는 테이블 상에서 AUTO INCREMENT를 통해 만들어지고 있기 때문에 빼놓았습니다.

2024-04-01 12:42 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        UserRow userRow = userMapper.find(uuid);
넵넵

2024-04-01 12:45 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/model/User.java
> +public record User(Long userIdx, String uuid, String name, String id, String password) {
우선은 둘 중에 하나만 PK로 선택하고, 나중에 PK와 UUID를 분리할지 고민해 봅시다!

2024-04-01 12:47 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/mapper/UserMapper.java
> +    int create(String uuid, String name, String id, String password);
userIdx = null인 domain을 넘겨도 되지 않을까요?

2024-04-01 12:47 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/mapper/UserMapper.java
> +    int create(String uuid, String name, String id, String password);
CreateUserRow, UserRow로 분리하셔도 되는데, 취향껏..

2024-04-01 12:48 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/controller/UserController.java
> +         return ResponseEntity.ok(new JsonResponse(true, 200, userName));
이건 정말로 UI적인 부분이라 자유롭게 해주세요!

2024-04-01 12:48 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/dto/JsonResponse.java
> +    private int status;
ResponseEntity<UserResponse> 요 형태로 생각했습니다.

2024-04-01 12:49 UTC, blue000927 approved these changes
LGTM (Looks Good To Me)

2024-04-03 04:14 UTC, pjy1368 approved these changes

2024-04-05 10:36 UTC, blue000927 requested changes

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        // id 중복 체크
주석은 제거해주세요! 메서드 이름만으로 로직을 알 수 있게 구성해주세요

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +@Log4j2
지금 사용 안하지 않나요?

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +                .getLogin_id()).password(request.getPassword()).build();
보통 빌더는 다음과 같이 작성하는 편이에요
```java
User.builder()
.name()
.password()
.build();
```

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        System.out.println("insert count : " + insertCount);
System.out.println()은 개인적으로 테스트하실 때만 사용하시고, 실제 코드 올릴 때는 제거해 주세요. 로깅이 필요하다면 Sl4fj 같은 라이브러리를 활용해주세요.

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        }
1이 아니게 될 수가 있나요??
에러가 나면 0이 반환되기보다는 에러가 날 것 같은데, 한번 확인해주세요!
왠지 userMapper.register() 과정에서 실패하지 않을까 싶네요.

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/config/exception/ExceptionAdvice.java
> +        body.put("error", ex.getStatus().getMessage());
ExceptionReponse 관련 DTO를 만들면 어떨까요?

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/config/exception/ExceptionAdvice.java
> +
주석 제거

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/User.java
> +
한 줄 제거

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/User.java
> +
한 줄 제거 (PR 올리기 전에 꼭 전체 코드 포매팅 해주세요)

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/User.java
> +    private final String login_id;
왜 네이밍을 snake case로 했나요?

2024-04-05 10:36 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/User.java
> +    }
요거 롬복으로 줄여보면 어떨까요?

2024-04-05 10:36 UTC, blue000927 commented on src/main/resources/mapper/UserMapper.xml
> +    </select>
이정도 간단한 쿼리는 Mapper 단에서 어노테이션 안에 작성해도되지 않을까요?
추가) 데이터 존재여부 확인할 때는 exists 쿼리를 사용해보세요!

2024-04-05 10:36 UTC, blue000927 commented on src/main/resources/schema.sql
> +CREATE TABLE Users (
DB 테이블은 주로 소문자로 작성합니다. (ex. users)

2024-04-05 10:36 UTC, blue000927 commented on src/test/java/com/example/soundhub/controller/UserControllerTest.java
> +@TestPropertySource(locations = "classpath:application-test.yml")
이건 왜 필요한가요?

2024-04-05 10:36 UTC, blue000927 commented on src/test/java/com/example/soundhub/controller/UserControllerTest.java
> +@ExtendWith(SpringExtension.class)
이 extendWith는 왜 필요한가요?

2024-04-05 10:36 UTC, blue000927 commented on src/test/java/com/example/soundhub/controller/UserControllerTest.java
> +    }
[REST Assured](https://rest-assured.io/) 이용해서 테스트 코드 작성해보시면 어떨까요?

2024-04-05 10:36 UTC, blue000927 commented on src/test/java/com/example/soundhub/mapper/UserMapperTest.java
> +        jdbcTemplate.update("DELETE FROM Users");
테이블의 모든 데이터 지울 때는 TRUNCATE 사용하시는 것이 성능상 더 좋습니다. (왜 그럴까요?)

2024-04-05 10:36 UTC, blue000927 commented on src/test/java/com/example/soundhub/mapper/UserMapperTest.java
> +        System.out.println("user ID : " + user.getId());
제거

2024-04-05 10:36 UTC, blue000927 commented on src/test/java/com/example/soundhub/service/UserServiceTest.java
> +public class UserServiceTest {
서비스 테스트하는데 Controller가 왜 필요할까요?

2024-04-05 10:36 UTC, blue000927 commented on src/test/java/com/example/soundhub/service/UserServiceTest.java
> +        given(userMapper.register(any(User.class))).willReturn(1);
@SpringBootTest는 빈을 모두 띄우는 것인데, Mapper를 모킹할 것이면 @SpringBootTest를 제거해도 되지 않을까요?
모킹할 때는 보통 빈을 띄우지 않거나 최소로 띄우고, 모킹을 하지 않을 때만 빈을 많이 띄웁니다.
물론 후자의 경우도 모든 빈을 띄우면 테스트 속도가 느리기 때문에 필요한 빈만 등록하는 편이에요. (ex. DB, Mapper)

2024-04-06 07:36 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        }
현재 userMapper의 register 반환 값은 int로 설정되었을 때의 기본 값인 성공 시 1 실패 시 0을 반환하도록 되어있기 때문에 성공적인 insert가 이루어졌을 경우에만 1을 반환하도록 되어있습니다!

2024-04-06 07:39 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        }
아 방금 커밋한 기준으로는 xml 파일에서 유저 PK를 반환하도록 하고 있네요.. 현재 회원가입 서비스 로직에서는 유저 PK가 필요하지 않아서 앞서 설명드린 방식대로 구현했습니다. 다음 커밋 때 xml 파일 수정하겠습니다!

2024-04-07 05:00 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/domain/User.java
> +    private final String login_id;
저번에 알려주신 예시대로 변경 했었습니다 !

2024-04-07 05:04 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/domain/User.java
> +    private final String login_id;
DB상에 저장되는 이름과 동일한 것이 좋을 것 같아서 맞췄습니다

2024-04-07 07:55 UTC, blue000927 commented on src/main/java/com/example/soundhub/domain/User.java
> +    private final String login_id;
Java이 네이밍 컨벤션은 camel case여서 DB상 이름과 동일은 하되 이 부분은 고쳐주세요!

2024-04-08 12:49 UTC, blue000927 approved these changes

2024-04-08 12:49 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        }
userMapper.register() 앞뒤 try ~ catch로 묶어서 예외 처리를 해보면 좋겠습니다. 지금 상황은 어떤 예외때문에 insert가 실패한지 알수가 없습니다!

2024-04-08 12:49 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +    }
이렇게 서비스에서 중복 체크를 검증하는 방법도 있고, 그냥 DB쪽에 중복 오류 터뜨려서 try~catch로 잡은뒤 catch로 Exception던지는 방법도 있어요. 요건 선택입니다!

2024-04-08 12:49 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/mapper/UserMapper.java
> +    int register(User user);
Mapper는 infra 계층이고, DB에 좀더 가까운 대상이에요.
그런데, register 같은 용어는 비즈니스에서 사용하는 용어이므로 register보다는 create라고 표현해 주시는 것이 더 적합합니다.

2024-04-08 12:49 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/mapper/UserMapper.java
> +    boolean existsByLoginId(String login_id);
login_id -> loginId

2024-04-08 12:49 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/dto/request/UserRequest.java
> +        private String login_id;
loginId

2024-04-08 12:49 UTC, blue000927 commented on src/main/resources/mapper/UserMapper.xml
> +    </select>
rm

2024-04-08 12:49 UTC, blue000927 commented on src/main/resources/schema.sql
> +        password VARCHAR(255) NOT NULL,
255보다 작게 가져가도 되지 않을까요? (Optional)

2024-04-08 12:49 UTC, blue000927 commented on src/test/java/com/example/soundhub/controller/UserControllerTest.java
> +        assertEquals(expectedResponse, createResponse.body().asString());
given, when, then으로 주석을 쓰거나 생략하거나 하면 좋을 것 같습니다.

2024-04-08 12:49 UTC, blue000927 commented on src/test/java/com/example/soundhub/controller/UserControllerTest.java
> +@ActiveProfiles("test")
지금은 h2 DB를 테스트 용도로 쓰고 있는데, prod은 mysql DB를 사용하고 있습니다.
그러면 h2 DB와 mysql DB 간의 차이 때문에 간혹가다가 테스트는 성공하는데 실제 케이스에서는 실패하는 경우가 있습니다.
이럴 때는 testContainers 혹은 로컬에 mysql test DB를 연결하는 편입니다. 
(지금 하진 마시고 참고)

2024-04-08 12:49 UTC, blue000927 commented on src/test/java/com/example/soundhub/mapper/UserMapperTest.java
> +    @Autowired
한 칸 띄웁시다.

2024-04-08 12:49 UTC, blue000927 commented on src/test/java/com/example/soundhub/mapper/UserMapperTest.java
> +    void register() {
create로 변경

2024-04-08 12:49 UTC, blue000927 commented on src/test/java/com/example/soundhub/mapper/UserMapperTest.java
> +    void idCheck() {
existsXXX로 볒ㄴ경

2024-04-08 12:49 UTC, blue000927 commented on src/test/java/com/example/soundhub/mapper/UserMapperTest.java
> +        Assertions.assertEquals(user, foundUser);
assertJ 사용해서 바꿔보시면 좋을 것 같습니다. 아마 써 보시면 이게 왜 좋은지 알거예요 ㅎㅎ

2024-04-12 08:26 UTC, merged