[FEAT] #7 : JWT 기능 및 필터 구현, 로그인 기능 추가
f-lab-edu/sound-hub pull request #8
Opened 2024-04-13 15:44 UTC by dhchoi98

2024-04-14 08:44 UTC, blue000927 requested changes

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        User user = User.builder().name(request.getName()).loginId(request.getLoginId()).password(request.getPassword()).build();
```java
User.builder()
.name()
.loginId()
...
```
방식같은 체이닝으로 써 보면 어떨까요?

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +            throw new BadRequestException(REGISTER_USER_ERROR);
create() operation에서 발생할 수 있는 예외는 중복된 레코드 등록, nullable/non-nullable 잘못된 매핑 등이 있는데요! 쿼리로 중복체크하여 throw하기보다는 아예 여기 try~catch에서 한 번에 잡아서 처리하면 어떨까요?

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> +        }
현재 CRUD 쿼리마다 service 단에서 trycatch를 묶어 주고 있습니다.
만약 findUserByLoginId()를 사용하는 경우가 많으면 매번 trycatch를 사용해야할텐데 어떻게 하면 좋을까요? (힌트: DAO)

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtUtil.java
> +public class JwtUtil {
왜 빈으로 등록하셨나요?

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtUtil.java
> +    long refreshTokenValidity = 1000 * 60 * 60 * 24 * 7;
환경 변수로 빼면 어떨까요?

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtUtil.java
> +        claims.put("type", "Access");
상수로 빼 보면 어떨까요?

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtUtil.java
> +        UserResponse.tokenInfo tokenInfo = UserResponse.tokenInfo.builder().grantType("Bearer").accessToken(accessToken).refreshToken(refreshToken).build();
체이닝 방식으로 빌더 패턴 코드 작성해 보면 어떨까요?

2024-04-14 08:44 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtTokenFilter.java
> +public class JwtTokenFilter implements Filter {
Interceptor가 아닌 Filter를 사용한 이유가 있으신가요?

2024-04-15 11:50 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtUtil.java
> +public class JwtUtil {
이거 다시 보니까 내부에 secret-key 같은 것들을 static으로 선언하면, `@Value`를 못 쓰기 때문에 빈으로 등록하는 것이 맞겠네요!
왜 static과 `@Value`는 같이 못 쓰는지 한 번 생각해 보세요 ~~

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/config/exception/ErrorResponseStatus.java
> +    DUPLICATE_ID(false, 2002, "중복된 아이디 입니다."),
이정도는 DUPLICATE_ERROR로 퉁쳐보면 어떨까요? 나중에 비슷한 중복 체크가 많아지면 번거로워질듯합니다!

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/application/service/UserService.java
> -        } catch (DataAccessException e) {
여기도 userDao.create() 만들면 어떨까요?

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/config/exception/ExceptionAdvice.java
> +    }
모든 데이터베이스 예외가 400번일까요?

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtTokenFilter.java
> +
2줄 지우기

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtUtil.java
> +
1줄 지우기

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/presentation/dto/request/UserRequest.java
> +        @Pattern(regexp = "^[ㄱ-ㅎ가-힣a-z0-9-_]{2,10}$", message = "이름은 특수문자를 제외한 2~12 자리여야 합니다.")
해당 예외를 처리하는 ExceptionHandler를 정의해야하지않을까요?

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/config/exception/DatabaseException.java
> +public class DatabaseException extends RuntimeException{
`RuntimeException {`

2024-04-19 15:09 UTC, blue000927 commented on src/main/java/com/example/soundhub/jwt/JwtTokenFilter.java
> +                String refreshToken = httpRequest.getHeader("Refresh");
필터에서 발생한 예외는 RestControllerAdvice에서 왜 안잡힐까요?

2024-04-25 02:22 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/jwt/JwtTokenFilter.java
> +                String refreshToken = httpRequest.getHeader("Refresh");
ExceptionHandler 메소드를 작성하지 않아주어서 그렇습니다 수정하겠습니다 !

2024-04-25 02:22 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/presentation/dto/request/UserRequest.java
> +        @Pattern(regexp = "^[ㄱ-ㅎ가-힣a-z0-9-_]{2,10}$", message = "이름은 특수문자를 제외한 2~12 자리여야 합니다.")
추가하겠습니다 !!

2024-04-25 02:22 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/config/exception/ExceptionAdvice.java
> +    }
DB Internal 에러는 500번을 반환하도록 수정했습니다 !!

2024-04-25 12:55 UTC, blue000927 approved these changes
고생 많았어요! 이후 작업 열심히 부탁드립니다 ㅎㅎ

2024-04-25 12:55 UTC, blue000927 commented on src/main/java/com/example/soundhub/config/WebConfig.java
> +    private JwtInterceptor jwtInterceptor;
생성자 주입으로 해주시죠!

2024-04-25 12:55 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/dao/UserDao.java
> +	}
Dao 입장에서는 create의 반환 타입은 User로 해주시죠~

2024-04-25 12:55 UTC, blue000927 commented on src/main/java/com/example/soundhub/infrastructure/dao/UserDao.java
> +	}
userMapper.find()로 해 옵시다. (추후 mapper단 insert하면서 User 받아오는 법 찾아보기)

2024-04-25 12:55 UTC, blue000927 commented on src/main/resources/application-test.yml
> +  secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
뭔가 너무 진짜 값 같이 생겼는데 ㅋㅋㅋ 그냥 test 정도로 쓰셔도 됩니다.

2024-04-25 13:17 UTC, dhchoi98 commented on src/main/resources/application-test.yml
> +  secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
test로 썼을 때 메인 어플리케이션에서 오류가나서 바꿨습니다ㅠㅠ

2024-04-25 13:54 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/infrastructure/dao/UserDao.java
> +	}
insert하면서 User 객체를 반환 받는건 안되고 id 같은 필드만 가능하다고 합니다 !

2024-04-25 14:19 UTC, dhchoi98 commented on src/main/java/com/example/soundhub/config/WebConfig.java
> +    private JwtInterceptor jwtInterceptor;
넵 !

2024-04-26 08:27 UTC, merged